# Generated by Django 5.0.1 on 2024-01-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('thumbnail_url', models.CharField(max_length=2048)),
                ('publishedAt', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
